services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: ip-location-app-local
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=your-development-secret-key-change-this-in-production
      # You can use either ADMIN_PASSWORD for plain text or ADMIN_PASSWORD_HASH for pre-hashed password
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-password}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-}
      - NEXT_PUBLIC_IP_API_URL=http://ip-api.com/json
      - NEXT_PUBLIC_IP_API_FIELDS=query,city,country,countryCode,region,regionName,district,zip,lat,lon,timezone,isp,org,as,reverse,mobile,proxy,hosting
      - NEXT_PUBLIC_CORS_ORIGIN=*
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: npm run dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  default:
    name: ip-location-app-local-network
    driver: bridge
