version: '3.8'

services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}  # Change this in production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge