services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2b$10$0OXdnHEfFl4vDR4NRnxHfezacsmjqpXLo8Hmjtp2woPei35ySbzi6}
      - NEXT_PUBLIC_IP_API_URL=http://ip-api.com/json
      - NEXT_PUBLIC_IP_API_FIELDS=query,city,country,countryCode,region,regionName,district,zip,lat,lon,timezone,isp,org,as,reverse,mobile,proxy,hosting
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - app_network

networks:
  app_network:
    driver: bridge