version: '3.8'

services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    container_name: ip-location-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-secret-key-here}
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
