version: '3.8'

services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    container_name: ip-location-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=your-random-secret-key-change-this
      # CORS settings
      - NEXT_PUBLIC_IP_API_URL=http://ip-api.com/json
      - NEXT_PUBLIC_ENABLE_IP_LOCATION=true
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app_network:
    driver: bridge