version: '3.8'

services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_SECRET=your-random-secret-key-change-this
