version: '3.8'

services:
  app:
    image: ghcr.io/skpokala/ip-location-app:latest
    container_name: ip-location-app
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=http://localhost:4000
      - NEXTAUTH_SECRET=your-random-secret-key-change-this
      - NEXT_PUBLIC_IP_API_URL=http://ip-api.com/json
      - NEXT_PUBLIC_IP_API_FIELDS=query,city,country,countryCode,region,regionName,district,zip,lat,lon,timezone,isp,org,as,reverse,mobile,proxy,hosting
